/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentList: typeof import('./src/components/admin/AgentList.vue')['default']
    AIFloatingBall: typeof import('./src/components/AIFloatingBall.vue')['default']
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/Layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/Layout/AppSidebar.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    CombinedAIConfig: typeof import('./src/components/admin/CombinedAIConfig.vue')['default']
    DataCard: typeof import('./src/components/DataCard.vue')['default']
    FeatureConfigList: typeof import('./src/components/admin/FeatureConfigList.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    ITablerBook2: typeof import('~icons/tabler/book2')['default']
    ITablerChartDots2: typeof import('~icons/tabler/chart-dots2')['default']
    ITablerChartLine: typeof import('~icons/tabler/chart-line')['default']
    ITablerChecklist: typeof import('~icons/tabler/checklist')['default']
    ITablerCpu: typeof import('~icons/tabler/cpu')['default']
    ITablerFileText: typeof import('~icons/tabler/file-text')['default']
    ITablerLayoutDashboard: typeof import('~icons/tabler/layout-dashboard')['default']
    ITablerSettings: typeof import('~icons/tabler/settings')['default']
    ITablerSparkles: typeof import('~icons/tabler/sparkles')['default']
    ITablerTools: typeof import('~icons/tabler/tools')['default']
    ITablerUsers: typeof import('~icons/tabler/users')['default']
    LogViewer: typeof import('./src/components/admin/LogViewer.vue')['default']
    RankingList: typeof import('./src/components/RankingList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskChart: typeof import('./src/components/Charts/TaskChart.vue')['default']
    TextFlip: typeof import('./src/components/Effects/TextFlip.vue')['default']
    TrendChartModule: typeof import('./src/components/TrendChartModule.vue')['default']
    UserManagement: typeof import('./src/components/admin/UserManagement.vue')['default']
  }
}
