/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentList: typeof import('./src/components/admin/AgentList.vue')['default']
    AIFloatingBall: typeof import('./src/components/AIFloatingBall.vue')['default']
    AppHeader: typeof import('./src/components/Layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/Layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/Layout/AppSidebar.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    CombinedAIConfig: typeof import('./src/components/admin/CombinedAIConfig.vue')['default']
    DataCard: typeof import('./src/components/DataCard.vue')['default']
    FeatureConfigList: typeof import('./src/components/admin/FeatureConfigList.vue')['default']
    FilterBar: typeof import('./src/components/FilterBar.vue')['default']
    LogViewer: typeof import('./src/components/admin/LogViewer.vue')['default']
    RankingList: typeof import('./src/components/RankingList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskChart: typeof import('./src/components/Charts/TaskChart.vue')['default']
    TextFlip: typeof import('./src/components/Effects/TextFlip.vue')['default']
    TrendChartModule: typeof import('./src/components/TrendChartModule.vue')['default']
    UserManagement: typeof import('./src/components/admin/UserManagement.vue')['default']
  }
}
