"""Add TaskRecord and JielongRecord models

Revision ID: 59ad61644acc
Revises: 
Create Date: 2025-11-03 13:57:20.228572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ad61644acc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jielong_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('intention', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jielong_records_id'), 'jielong_records', ['id'], unique=False)
    op.create_index(op.f('ix_jielong_records_student_id'), 'jielong_records', ['student_id'], unique=False)
    op.create_table('task_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_records_id'), 'task_records', ['id'], unique=False)
    # op.drop_table('sqlite_sequence')  # Commented out as sqlite_sequence is a system table
    op.alter_column('task_completions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_task_completions_id'), 'task_completions', ['id'], unique=False)
    op.alter_column('task_jielong_entries', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_task_jielong_entries_id'), 'task_jielong_entries', ['id'], unique=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.alter_column('tasks', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_task_jielong_entries_id'), table_name='task_jielong_entries')
    op.alter_column('task_jielong_entries', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_task_completions_id'), table_name='task_completions')
    op.alter_column('task_completions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # op.create_table('sqlite_sequence',  # Commented out as sqlite_sequence is a system table
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    op.drop_index(op.f('ix_task_records_id'), table_name='task_records')
    op.drop_table('task_records')
    op.drop_index(op.f('ix_jielong_records_student_id'), table_name='jielong_records')
    op.drop_index(op.f('ix_jielong_records_id'), table_name='jielong_records')
    op.drop_table('jielong_records')
    # ### end Alembic commands ###
